# -*- coding: utf-8 -*-
"""multi_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkqbJx65ANjqJqonwWsgjosp26Gsuw1p
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile multiapp.py

import streamlit as st

class MultiApp:
    def __init__(self):
        self.apps = []

    def add_app(self, title, func):
        self.apps.append({
            "title": title,
            "function": func
        })

    def run(self):
        app = st.sidebar.selectbox(
            'Select your choice from drop down list',
            self.apps,
            format_func=lambda app: app['title'])

        app['function']()